AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Metrics/MethodLength:
  Max: 40

Metrics/ClassLength:
  Max: 200

Layout/LineLength:
  Max: 120

Naming/AccessorMethodName:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'lib/tomba/services/leads-attributes.rb'
    - 'lib/tomba/services/leads-lists.rb'

Metrics/AbcSize:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/ParameterLists:
  Max: 7
